export const initialState: any = {
  activeTitle: 'По проекту',
  'По проекту': [
    {
      id: 1,
      title: '',
      unit: '',
      quantity: 0,
      unitPrice: 0,
      price: 0,
      parent: null,
      type: 'level',
      color: null,
    },
  ],
  Объекты: [
    {
      id: 1,
      title: '',
      unit: '',
      quantity: 0,
      unitPrice: 0,
      price: 0,
      parent: null,
      type: 'level',
      color: null,
    },
  ],
  РД: [
    {
      id: 1,
      title: '',
      unit: '',
      quantity: 0,
      unitPrice: 0,
      price: 0,
      parent: null,
      type: 'level',
      color: null,
    },
  ],
  МТО: [
    {
      id: 1,
      title: '',
      unit: '',
      quantity: 0,
      unitPrice: 0,
      price: 0,
      parent: null,
      type: 'level',
      color: null,
    },
  ],
  СМР: [
    {
      id: 1,
      title: '',
      unit: '',
      quantity: 0,
      unitPrice: 0,
      price: 0,
      parent: null,
      type: 'level',
      color: null,
    },
  ],
  График: [
    {
      id: 1,
      title: '',
      unit: '',
      quantity: 0,
      unitPrice: 0,
      price: 0,
      parent: null,
      type: 'level',
      color: null,
    },
  ],
  МиМ: [
    {
      id: 1,
      title: '',
      unit: '',
      quantity: 0,
      unitPrice: 0,
      price: 0,
      parent: null,
      type: 'level',
      color: null,
    },
  ],
  Рабочие: [
    {
      id: 1,
      title: '',
      unit: '',
      quantity: 0,
      unitPrice: 0,
      price: 0,
      parent: null,
      type: 'level',
      color: null,
    },
  ],
  Капвложения: [
    {
      id: 1,
      title: '',
      unit: '',
      quantity: 0,
      unitPrice: 0,
      price: 0,
      parent: null,
      type: 'level',
      color: null,
    },
  ],
  Бюджет: [
    {
      id: 1,
      title: '',
      unit: '',
      quantity: 0,
      unitPrice: 0,
      price: 0,
      parent: null,
      type: 'level',
      color: null,
    },
  ],
  Финансирование: [
    {
      id: 1,
      title: '',
      unit: '',
      quantity: 0,
      unitPrice: 0,
      price: 0,
      parent: null,
      type: 'level',
      color: null,
    },
  ],
  Панорамы: [
    {
      id: 1,
      title: '',
      unit: '',
      quantity: 0,
      unitPrice: 0,
      price: 0,
      parent: null,
      type: 'level',
      color: null,
    },
  ],
  Камеры: [
    {
      id: 1,
      title: '',
      unit: '',
      quantity: 0,
      unitPrice: 0,
      price: 0,
      parent: null,
      type: 'level',
      color: null,
    },
  ],
  Поручения: [
    {
      id: 1,
      title: '',
      unit: '',
      quantity: 0,
      unitPrice: 0,
      price: 0,
      parent: null,
      type: 'level',
      color: null,
    },
  ],
  Контрагенты: [
    {
      id: 1,
      title: '',
      unit: '',
      quantity: 0,
      unitPrice: 0,
      price: 0,
      parent: null,
      type: 'level',
      color: null,
    },
  ],
};
